[package]
name = "cand"
version = "0.1.0"
authors = ["fridtjof <2780577+fridtjof@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libusb = "0.3.0"
getopts = "0.2.18"
crc16 = "0.4.0"
nix = "0.13.0"