[package]
name = "cand"
version = "0.1.0"
authors = ["fridtjof <2780577+fridtjof@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crc16 = "0.4.0"
tokio = "0.1"
tokio-serial = "3.2"
bytes = "0.4"

num = "0.2"
num-traits = "0.2"
num-derive = "0.2"